### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ghost** [wnielson/nzbverify#1]
This is what happens when I try to run.

What might I be missing?

thanks

nzbverify version 0.3.0, Copyright (C) 2014 Weston Nielson wnielson@github
Found 1 primary host
   news.newshosting.com
Found 0 backup hosts
Created 1/1 threads
Parsing NZB: nzbs/ubuntu.nzb
Exception in thread thread-0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/nzbverify/thread.py", line 32, in run
    connection = self.server.create_connection()
  File "/usr/local/lib/python2.7/dist-packages/nzbverify/server.py", line 37, in create_connection
    self.conf.get("use_ssl"), self.conf.get("timeout"))
  File "/usr/local/lib/python2.7/dist-packages/nzbverify/nntp.py", line 58, in __init**
    if 'STARTTLS' in self.getcapabilities():
TypeError: argument of type 'NoneType' is not iterable

Found 47 files and 5604 segments totaling 3.99 GB
Available:    0 [0.00%], Missing:    0 [0.00%], Total:    0 [0.00%]

**Comment by wnielson** [comment]
Fixed in #2
